Demo_Dbt:
  outputs:
    dev:
      account: hk68763.ap-southeast-1
      password: Bhagyesh#2001
      role: ACCOUNTADMIN
      database: SNOWFLAKE_SAMPLE_DATA
      schema: TPCH_SF1
      threads: 10
      type: snowflake
      user: BHAGYESHBHUT
      warehouse: COMPUTE_WH
  target: dev
